server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-authuser-v2
    username: postgres
    password: 038921
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: Always
  rabbitmq:
    addresses: amqps://ygmomiyf:Aq2L9cVlPIGp6xMAY3ex_MQB5gFcMRNQ@beaver.rmq.cloudamqp.com/ygmomiyf


ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

authuser:
  refreshscope:
    name: Andrea Lopes ATUALIZADO

management:
  endpoints:
    web:
      exposure:
        include:
          - refreshscope
          - health


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO



resilience4j:
  circuitbreaker:
    instances:
      circuitbreakerInstance:
        sliding-window-size: 30
        permitted-number-of-calls-in-half-open-state: 2
        sliding-window-type: TIME_BASED
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 15s
        failure-rate-threshold: 80
  retry:
    instances:
      retryInstance:
        max-attempts: 3
        wait-duration: 5s

